services:
  - type: web
    name: wordy-kids-app
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: wordy-kids-app
          property: port
    domains:
      - wordy-kids.onrender.com
